# Network of springs
Solve equations to calculate mechanical equilibrium in network of springs. The theoretical background of the exercise is covered in Section 2.1 of the script to this lecture.

In [41]:
import numpy as np
np.set_printoptions(formatter={'float': '{: >10.3f}'.format})

## Task 1
Fill in the missing code segments marked by "..." and set the spring constant ``ka`` to the last two digits of your student number

In [42]:
# Initialize variables
F = np.zeros(3) # [0, 0, 0]
u = np.zeros(3) # [0, 0, 0]
K = np.zeros((3, 3)) 

# Define stiffness matrix
# XY are last two digits of your student number (if zero, use XY=20)
XY = 64
ka = XY       # spring constant a (unit 1 N/mm)
kb = 0.5*ka   # spring constant b (unit 1 N/mm)

# stiffness matrix of spring 1
ks1 = np.array([[ka, -ka, 0],
                [-ka, ka, 0],
                [0, 0, 0]])   

# Missing code segments:
# Stiffness matrix of spring 2
ks2 = np.array([[0, 0, 0],
                [0, kb, -kb],
                [0, -kb, kb]])   

# system stiffness matrix
K = np.array([[ka, -ka, 0],
                [-ka, ka+kb, -kb],
                [0, -kb, kb]])  
print('System stiffness matrix:\n', K)

# Apply boundary conditions
F[2] = 100.
u[0] = 0.
for i in range(1, 3):
    # Reduce rank of system of equations for given displacement BC
    F[i] -= K[i, 0] * u[0]

# Solve reduced system of equations
u[1:3] = np.linalg.solve(K[1:3, 1:3], F[1:3])
print('After solving reduced system of equations:\n',
      'u: ', u, '\nF: ', F)

F = K@u # calculate reaction forces
print('After calculation of reaction forces:\n',
      'u: ', u, '\nF: ', F)

System stiffness matrix:
 [[    64.000    -64.000      0.000]
 [   -64.000     96.000    -32.000]
 [     0.000    -32.000     32.000]]
After solving reduced system of equations:
 u:  [     0.000      1.562      4.687] 
F:  [     0.000      0.000    100.000]
After calculation of reaction forces:
 u:  [     0.000      1.562      4.687] 
F:  [  -100.000      0.000    100.000]


## Task 2
Fill in the missing code segment, to apply a displacement of u=15 at the rhs node instead of the force BC.

In [43]:
# Apply boundary conditions
u[0] = 0.   # displacement (unit 1mm)
u[2] = 15.  # displacement (unit 1mm)

F = np.zeros(3)

for i in range(1, 2):
    # Missing code segment:
    # Reduce rank of system of equations for given displacement BC
      F[i] -= K[i, 0] * u[0]
      F[i] -= K[i, 2] * u[2]

    
# Solve reduced system of equations
u[1:2] = np.linalg.solve(K[1:2, 1:2], F[1:2])
print('After solving reduced system of equations:\n',
      'u: ',u, '\nF: ',F)

F = K@u # Calculate reaction force
print('After calculation of reaction forces:\n',
      'u: ',u, '\nF: ',F)

After solving reduced system of equations:
 u:  [     0.000      5.000     15.000] 
F:  [     0.000    480.000      0.000]
After calculation of reaction forces:
 u:  [     0.000      5.000     15.000] 
F:  [  -320.000      0.000    320.000]


## Task 3
Setup a system for an arbitrary number N springs (use N=4 as example, and take random spring constants in the range 10N/mm to 100N/mm). Calculate the nodal forces and displacements under mechanical equilibrium under the same boundary conditions as in Task 2.

In [44]:
def setupK(N):
    """
    Setup a stiffness matrix for N springs, i.e. N+1 nodes
    
    N : integer, referring to the number of springs
    """
    K = np.zeros((N+1, N+1))
    # Initialize rand number generator
    rng = np.random.default_rng(42)
    # Calculate random spring constants in range 10-100
    k0 = 10. + rng.random(N) * 90.  
    for i in range(N):
        # Missing code segment:
        # Insert spring stiffness matrix into system stiffness matrix
        K[i:i+2, i:i+2] += np.array([[k0[i],-k0[i]],[-k0[i],k0[i]]])
        
    return K

# Initialize system arrays and setup stiffness matrix K
N = 4
F = np.zeros(N+1)
u = np.zeros(N+1)
K = setupK(N)
print('System stiffness matrix:\n', K)

# Apply boundary conditions
u[0] = 0.
u[N] = 15.

for i in range(1,N):
    # Missing code segments:
    #F[i] ...    # reduce rank of system of equations for given displacement BC
    F[i] -= K[i, 0] * u[0]
    F[i] -= K[i, 2] * u[2]
                                     
# Solve reduced system of equations
u[1:N] = np.linalg.solve(K[1:N, 1:N], F[1:N])
print('After solving reduced system of equations:\n')#,
#       'u: ',u, '\nF: ',F)
print(u)
print(F)

F = K@u # calculate reaction force
print('After calculation of reaction forces:\n')#,'u: ',u, '\nF: ',F)
print(u)
print(F)


System stiffness matrix:
 [[    79.656    -79.656      0.000      0.000      0.000]
 [   -79.656    129.155    -49.499      0.000      0.000]
 [     0.000    -49.499    136.773    -87.274      0.000]
 [     0.000      0.000    -87.274    160.037    -72.763]
 [     0.000      0.000      0.000    -72.763     72.763]]
After solving reduced system of equations:

[     0.000      0.000      0.000      0.000     15.000]
[     0.000      0.000      0.000      0.000      0.000]
After calculation of reaction forces:

[     0.000      0.000      0.000      0.000     15.000]
[     0.000      0.000      0.000  -1091.447   1091.447]
